/**
 * Slice 299 (S4) — Source-of-Truth Boundary Ratchet-Guard.
 *
 * Enforces Master-Audit §11 Anti-Kreis-Regeln 5+6 ("keine neuen Imports auf
 * Bridge-Services / keine neuen Komponenten mit direktem Supabase-Zugriff")
 * WITHOUT forcing migration of the existing baseline (no Big-Bang refactor).
 *
 * Pattern mirrors scripts/silent-fail-audit.ts (.audit-baseline.json):
 *   - default      → write report to worklog/audits/<date>/
 *   - --check      → compare vs .boundary-baseline.json, exit 1 ONLY on increase
 *   - --update     → rewrite baseline to current live state (after a legit migration)
 *
 * Two tracked boundaries:
 *   1. BRIDGE imports  — `from '@/lib/services/<bridge>'` (re-export shims to
 *                        @/features/fantasy/services/*). Per-bridge count.
 *   2. Direct Supabase — component-layer files (src/components, src/app) that
 *                        import '@/lib/supabaseClient' directly.
 * __tests__ excluded (test imports are not a production boundary violation).
 */
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'fs';
import { join, relative } from 'path';

const ROOT = process.cwd();
const SRC = join(ROOT, 'src');
const BASELINE_PATH = join(ROOT, '.boundary-baseline.json');

// Slice 301 (S6): wildcards bridge (src/lib/services/wildcards.ts) removed — 0 importers (S4-F-1, RED/GREEN-proof).
const BRIDGES = ['fixtures', 'lineups', 'fantasyLeagues', 'scoring', 'events', 'predictions'] as const;
type Bridge = (typeof BRIDGES)[number];

interface BoundarySnapshot {
  bridges: Record<Bridge, number>;
  directSupabaseComponents: number;
}

interface Detail {
  bridgeImporters: Record<Bridge, string[]>;
  directSupabaseFiles: string[];
}

// --- file walk (exclude node_modules + __tests__) ---
function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (entry === 'node_modules' || entry === '__tests__' || entry === 'test-utils') continue;
      walk(full, acc);
    } else if (/\.(ts|tsx)$/.test(entry) && !/\.test\.(ts|tsx)$/.test(entry)) {
      acc.push(full);
    }
  }
  return acc;
}

function scan(): { snap: BoundarySnapshot; detail: Detail } {
  const files = walk(SRC);
  const bridgeImporters = Object.fromEntries(BRIDGES.map((b) => [b, [] as string[]])) as Record<Bridge, string[]>;
  const directSupabaseFiles: string[] = [];

  for (const file of files) {
    const rel = relative(ROOT, file).replace(/\\/g, '/');
    const content = readFileSync(file, 'utf-8');

    // 1. bridge imports — count one hit per (file, bridge) regardless of multiple lines.
    // Matches static `from '…'`, dynamic `import('…')` and `require('…')` (Slice 299 F-1:
    // from-only regex missed dynamic crossings like scoring.admin.ts await import()).
    // The bridge shim itself re-exports from @/features/… — never matches @/lib/services/<b>.
    for (const b of BRIDGES) {
      const re = new RegExp(`(from|import\\s*\\(|require\\s*\\()\\s*['"]@/lib/services/${b}['"]`);
      if (re.test(content)) bridgeImporters[b].push(rel);
    }

    // 2. direct supabase in component layer (src/components + src/app)
    const inComponentLayer = rel.startsWith('src/components/') || rel.startsWith('src/app/');
    if (inComponentLayer && /from ['"]@\/lib\/supabaseClient['"]/.test(content)) {
      directSupabaseFiles.push(rel);
    }
  }

  const snap: BoundarySnapshot = {
    bridges: Object.fromEntries(BRIDGES.map((b) => [b, bridgeImporters[b].length])) as Record<Bridge, number>,
    directSupabaseComponents: directSupabaseFiles.length,
  };
  return { snap, detail: { bridgeImporters, directSupabaseFiles } };
}

function totalBridges(s: BoundarySnapshot): number {
  return BRIDGES.reduce((sum, b) => sum + s.bridges[b], 0);
}

function writeReport(snap: BoundarySnapshot, detail: Detail) {
  // report folder date — env override for deterministic test runs, else today
  const date = process.env.AUDIT_DATE ?? new Date().toISOString().slice(0, 10);
  const dir = join(ROOT, 'worklog', 'audits', date);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = join(dir, 's4-source-of-truth-boundaries-report.md');
  const lines: string[] = [];
  lines.push(`# S4 Source-of-Truth Boundary Report — ${date}`, '');
  lines.push(`Generated by scripts/boundary-check.ts (Slice 299).`, '');
  lines.push(`## Bridge imports (\`@/lib/services/<bridge>\` → re-export shim)`, '');
  lines.push(`| Bridge | Importers |`, `|--------|----------:|`);
  for (const b of BRIDGES) lines.push(`| ${b} | ${snap.bridges[b]} |`);
  lines.push(`| **total** | **${totalBridges(snap)}** |`, '');
  lines.push(`## Direct \`@/lib/supabaseClient\` in component layer: ${snap.directSupabaseComponents}`, '');
  for (const f of detail.directSupabaseFiles) lines.push(`- ${f}`);
  lines.push('');
  writeFileSync(path, lines.join('\n'));
  console.log(`Report: ${relative(ROOT, path)}`);
}

// --- main ---
const mode = process.argv.includes('--check') ? 'check' : process.argv.includes('--update') ? 'update' : 'report';
const { snap, detail } = scan();

console.log('═══ Boundary-Check (Slice 299, S4) ═══');
console.log(`Bridge importers total: ${totalBridges(snap)}  (${BRIDGES.map((b) => `${b}:${snap.bridges[b]}`).join(' ')})`);
console.log(`Direct-Supabase component-layer files: ${snap.directSupabaseComponents}`);

if (mode === 'update') {
  writeFileSync(BASELINE_PATH, JSON.stringify(snap, null, 2) + '\n');
  console.log(`✅ Baseline updated → ${relative(ROOT, BASELINE_PATH)}`);
  process.exit(0);
}

if (mode === 'check') {
  if (!existsSync(BASELINE_PATH)) {
    writeFileSync(BASELINE_PATH, JSON.stringify(snap, null, 2) + '\n');
    console.log(`[--check] no baseline yet — wrote initial to ${relative(ROOT, BASELINE_PATH)}`);
    process.exit(0);
  }
  const baseline = JSON.parse(readFileSync(BASELINE_PATH, 'utf-8')) as BoundarySnapshot;
  const violations: string[] = [];
  for (const b of BRIDGES) {
    if (snap.bridges[b] > (baseline.bridges[b] ?? 0)) {
      violations.push(`bridge "${b}": ${snap.bridges[b]} > ${baseline.bridges[b] ?? 0} (baseline)`);
    }
  }
  if (snap.directSupabaseComponents > baseline.directSupabaseComponents) {
    violations.push(`direct-supabase components: ${snap.directSupabaseComponents} > ${baseline.directSupabaseComponents} (baseline)`);
  }
  if (violations.length > 0) {
    console.error('❌ Boundary regression — new source-of-truth violation(s):');
    for (const v of violations) console.error(`  • ${v}`);
    console.error('');
    console.error('Master-Audit §11.5/6: no new bridge imports / no new direct-Supabase components.');
    console.error('Import from @/features/fantasy/services/* (impl) or a query-facade instead.');
    console.error('If this was an intentional migration that LOWERED counts, run: pnpm run audit:boundary -- --update');
    process.exit(1);
  }
  console.log('✅ No boundary increase vs baseline. All source-of-truth boundaries held.');
  process.exit(0);
}

// report mode
writeReport(snap, detail);
process.exit(0);
