/**
 * Slice 300 (S5) — Test-Confidence Ratchet-Guard.
 *
 * Enforces Master-Audit §11.4 ("keine Testanzahl als Vertrauen, solange
 * Placeholder/Skipped nicht getrennt sind") — prevents NEW false-green tests
 * WITHOUT forcing migration of the existing baseline.
 *
 * Pattern = patterns.md #49 Baseline-Ratchet-Guard (3rd instance after
 * silent-fail-audit + boundary-check). Modi:
 *   - default   → write report to worklog/audits/<date>/
 *   - --check   → compare vs .test-confidence-baseline.json, exit 1 ONLY on increase
 *   - --update  → rewrite baseline to current state (after a legit cleanup)
 *
 * Two tracked signals (per .test.ts(x) file):
 *   1. placeholders — `expect(true).toBe(true)` / `expect(true).toBeTruthy()`
 *   2. skips        — it.skip / test.skip / describe.skip / xit / xdescribe / fit→no
 * Scans only *.test.ts(x). __tests__ dirs included (that IS where tests live).
 */
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'fs';
import { join, relative } from 'path';

const ROOT = process.cwd();
const SRC = join(ROOT, 'src');
const BASELINE_PATH = join(ROOT, '.test-confidence-baseline.json');

interface Snapshot {
  placeholders: number;
  skips: number;
}
interface Detail {
  placeholderFiles: { file: string; count: number }[];
  skipFiles: { file: string; count: number }[];
}

const PLACEHOLDER_RE = /expect\(\s*true\s*\)\.(toBe\(\s*true\s*\)|toBeTruthy\(\s*\))/g;
// Skip + focus markers (Slice 300 F-1): .skip silently drops a test; .only/fit
// silently drop ALL OTHERS (worse false-confidence). `fit(`/`xtest(` as CALLS only
// — bare `\bfit\b` false-positives on player status:'fit'.
const SKIP_RE = /\b(it|test|describe)\.(skip|only)\b|\bxit\b|\bxdescribe\b|\bfit\s*\(|\bxtest\s*\(/g;

function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (entry === 'node_modules') continue;
      walk(full, acc);
    } else if (/\.test\.(ts|tsx)$/.test(entry)) {
      acc.push(full);
    }
  }
  return acc;
}

function countMatches(content: string, re: RegExp): number {
  const m = content.match(re);
  return m ? m.length : 0;
}

function scan(): { snap: Snapshot; detail: Detail } {
  const files = walk(SRC);
  const placeholderFiles: { file: string; count: number }[] = [];
  const skipFiles: { file: string; count: number }[] = [];
  let placeholders = 0;
  let skips = 0;

  for (const file of files) {
    const rel = relative(ROOT, file).replace(/\\/g, '/');
    const content = readFileSync(file, 'utf-8');
    const p = countMatches(content, new RegExp(PLACEHOLDER_RE.source, 'g'));
    const s = countMatches(content, new RegExp(SKIP_RE.source, 'g'));
    if (p > 0) { placeholderFiles.push({ file: rel, count: p }); placeholders += p; }
    if (s > 0) { skipFiles.push({ file: rel, count: s }); skips += s; }
  }
  return { snap: { placeholders, skips }, detail: { placeholderFiles, skipFiles } };
}

function writeReport(snap: Snapshot, detail: Detail) {
  const date = process.env.AUDIT_DATE ?? new Date().toISOString().slice(0, 10);
  const dir = join(ROOT, 'worklog', 'audits', date);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = join(dir, 's5-test-confidence-report.md');
  const lines: string[] = [];
  lines.push(`# S5 Test-Confidence Report — ${date}`, '');
  lines.push(`Generated by scripts/test-confidence-check.ts (Slice 300).`, '');
  lines.push(`## Placeholder \`expect(true).toBe(true|Truthy)\`: ${snap.placeholders}`, '');
  for (const f of detail.placeholderFiles) lines.push(`- ${f.file} (${f.count})`);
  lines.push('', `## Skipped (\`*.skip\` / \`xit\` / \`xdescribe\`): ${snap.skips}`, '');
  for (const f of detail.skipFiles) lines.push(`- ${f.file} (${f.count})`);
  lines.push('');
  writeFileSync(path, lines.join('\n'));
  console.log(`Report: ${relative(ROOT, path)}`);
}

const mode = process.argv.includes('--check') ? 'check' : process.argv.includes('--update') ? 'update' : 'report';
const { snap, detail } = scan();

console.log('═══ Test-Confidence-Check (Slice 300, S5) ═══');
console.log(`Placeholder (expect(true)…): ${snap.placeholders}`);
console.log(`Skipped (*.skip / xit / xdescribe): ${snap.skips}`);

if (mode === 'update') {
  writeFileSync(BASELINE_PATH, JSON.stringify(snap, null, 2) + '\n');
  console.log(`✅ Baseline updated → ${relative(ROOT, BASELINE_PATH)}`);
  process.exit(0);
}

if (mode === 'check') {
  if (!existsSync(BASELINE_PATH)) {
    writeFileSync(BASELINE_PATH, JSON.stringify(snap, null, 2) + '\n');
    console.log(`[--check] no baseline yet — wrote initial to ${relative(ROOT, BASELINE_PATH)}`);
    process.exit(0);
  }
  const baseline = JSON.parse(readFileSync(BASELINE_PATH, 'utf-8')) as Snapshot;
  const violations: string[] = [];
  if (snap.placeholders > baseline.placeholders) {
    violations.push(`placeholders: ${snap.placeholders} > ${baseline.placeholders} (baseline)`);
  }
  if (snap.skips > baseline.skips) {
    violations.push(`skipped tests: ${snap.skips} > ${baseline.skips} (baseline)`);
  }
  if (violations.length > 0) {
    console.error('❌ Test-confidence regression — new false-green test(s):');
    for (const v of violations) console.error(`  • ${v}`);
    console.error('');
    console.error('Master-Audit §11.4: no new placeholder/skipped tests (green ≠ trust).');
    console.error('Write a Behavioral/Regression/Contract test instead, or document the skip honestly.');
    console.error('If this was an intentional cleanup that LOWERED counts, run: pnpm run audit:test-confidence -- --update');
    process.exit(1);
  }
  console.log('✅ No test-confidence increase vs baseline. Green stays meaningful.');
  process.exit(0);
}

writeReport(snap, detail);
process.exit(0);
