-- Applied via mcp__supabase__apply_migration (name: mystery_box_equipment_branch_fix)
-- Fix: equipment branch referenced v_reward_rec.equipment_type / .equipment_rank which
-- don't exist on mystery_box_config. Rank range lives in min_value/max_value; equipment
-- key is picked randomly from active equipment_definitions.
-- Also fixed the reward-weight accumulation to select from the row record instead of
-- a dependent sub-select.
-- Unmasked after the created_at → opened_at fix in 20260411114500.
